### ISSUE TITLE
Can't run apps

### ISSUE THREAD

**Issue by sarjanhanssan** [SimCoderYoutube/Uber_android_app_clone#1]
API 19 KitKat
It's crash and on logcat it returns,
`java.lang.RuntimeException: Unable to get provider com.google.firebase.provider.FirebaseInitProvider: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.provider.FirebaseInitProvider" on path: DexPathList[[zip file "/data/app/com.simcoder.uber-2.apk"],nativeLibraryDirectories=[/data/app-lib/com.simcoder.uber-2, /vendor/lib, /system/lib]]
                                                                       at android.app.ActivityThread.installProvider(ActivityThread.java:5236)
                                                                       at android.app.ActivityThread.installContentProviders(ActivityThread.java:4828)
                                                                       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4711)
                                                                       at android.app.ActivityThread.access$1600(ActivityThread.java:175)
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1368)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                       at android.os.Looper.loop(Looper.java:146)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:5602)
                                                                       at java.lang.reflect.Method.invokeNative(Native Method)
                                                                       at java.lang.reflect.Method.invoke(Method.java:515)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
                                                                       at dalvik.system.NativeStart.main(Native Method)
                                                                    Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.provider.FirebaseInitProvider" on path: DexPathList[[zip file "/data/app/com.simcoder.uber-2.apk"],nativeLibraryDirectories=[/data/app-lib/com.simcoder.uber-2, /vendor/lib, /system/lib]]
                                                                       at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:67)
                                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
                                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
                                                                       at android.app.ActivityThread.installProvider(ActivityThread.java:5221)
                                                                       at android.app.ActivityThread.installContentProviders(ActivityThread.java:4828) 
                                                                       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4711) 
                                                                       at android.app.ActivityThread.access$1600(ActivityThread.java:175) 
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1368) 
                                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                       at android.os.Looper.loop(Looper.java:146) 
                                                                       at android.app.ActivityThread.main(ActivityThread.java:5602) 
                                                                       at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                       at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283) 
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099) 
                                                                       at dalvik.system.NativeStart.main(Native Method) `

**Comment by DevJoseWeb** [comment]
erro in provider@
