### ISSUE TITLE
The app crashes

### ISSUE THREAD

**Issue by afosh** [SimCoderYoutube/Uber_android_app_clone#6]
when i click on register on my emulator
the app crashes and the logcat shows this error

04-14 15:22:50.640 7305-7305/com.simcoder.uber E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.simcoder.uber, PID: 7305
    java.lang.IllegalArgumentException: Given String is empty or null
        at com.google.android.gms.common.internal.zzbq.zzgi(Unknown Source:11)
        at com.google.firebase.auth.FirebaseAuth.createUserWithEmailAndPassword(Unknown Source:0)
        at com.simcoder.uber.CustomerLoginActivity$2.onClick(CustomerLoginActivity.java:58)
        at android.view.View.performClick(View.java:6256)
        at android.view.View$PerformClick.run(View.java:24701)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6541)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
04-14 15:22:50.640 7305-7305/com.simcoder.uber E/UncaughtException: java.lang.IllegalArgumentException: Given String is empty or null
        at com.google.android.gms.common.internal.zzbq.zzgi(Unknown Source:11)
        at com.google.firebase.auth.FirebaseAuth.createUserWithEmailAndPassword(Unknown Source:0)
        at com.simcoder.uber.CustomerLoginActivity$2.onClick(CustomerLoginActivity.java:58)
        at android.view.View.performClick(View.java:6256)
        at android.view.View$PerformClick.run(View.java:24701)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6541)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

**Comment by ahmadmust8** [comment]
because "Given String is empty or null"
in this class CustomerLoginActivity.java:   line : 58
